### ISSUE TITLE
Improve performance by using hashmaps

### ISSUE THREAD

**Issue by mrredo** [MalikWhitten67/html-dox#20]
for example here
https://github.com/MalikWhitten67/html-dox/blob/ee88b00d011057552fee8284a64148eb6d07b0b0/html-dox.js#L529-L555
instead of using an array and then checking it if it contains use a hashmap.
some  code:
```js
let accepted = {
"Accept":  true,
//other values
}
if (!accepted[header_name]) {
//error
}
```

**Comment by MalikWhitten67** [comment]
todo in next version

**Comment by MalikWhitten67** [comment]
obselete - all issues have been resolved
